  version: "3.3"
  networks:
    lnnet:
  
  volumes: 
    lnd-data:
    lnd-rest:
    btc-data:

  services:
    bitcoin:
      container_name: signet-btc
      image: dangershony/signet:0.20.1
      networks:
        - lnnet
      volumes:
        - btc-data:/root/.bitcoin
      expose:
        - "38332"
        - "38333"
      command: 
        - bitcoind
        - -signet
        - -server=1
        - -rpcallowip=0.0.0.0/0 
        - -rpcbind=bitcoin
        - -rpcpassword=rpcpassword
        - -rpcuser=user
        - -rpcport=38332
    
    lightning:
      container_name: signet-ln
      image: dangershony/clnd:0.9.1
      networks:
        - lnnet
      volumes:
        - lnd-rest:/rest
        - lnd-data:/root/.lightning
      expose:
        - "9735"
        - "4001"
      depends_on:
        - "bitcoin"
      command: 
        - lightningd
        - --network=signet
        - --bitcoin-rpcuser=user
        - --bitcoin-rpcpassword=rpcpassword
        - --bitcoin-rpcconnect=bitcoin
        - --bitcoin-rpcport=38332
        - --plugin=/rest/plugin.js
        - --rest-port=3002
        - --rest-docport=4001

    lightning-ui:
      container_name: signet-ui
      image: dangershony/clnd-rtl:latest
      networks:
        - lnnet
      volumes:
        - lnd-rest:/rest
      ports:
          - "0.0.0.0:3000:3000"
      depends_on:
        - "lightning"

    lightning-ui-proxy:
      container_name: signet-ui-proxy
      image: dangershony/clnd-rtl-proxy:latest
      networks:
        - lnnet
      ports:
        - "0.0.0.0:3002:3002"
        - "0.0.0.0:443:443"
      depends_on:
        - "lightning-ui"