## note: this i not used rather run from the link bellow (and replace the RTL-Config.json)
## https://github.com/Ride-The-Lightning/RTL/blob/master/docs/C-Lightning-setup.md

FROM shahanafarooqui/rtl:0.9.3


ADD RTL-Config.json /RTL

